mysite/urls.py
from django.conf.urls import url
from django.contrib import admin

from .apps.character.views import CharacterApi
from .apps.player.views import PlayerApi, PlayerRegist, RegistCancel
from .apps.scenario.views import ScenarioApi

urlpatterns = [
    url(r'^$', PlayerRegist.as_view(), name="regist"),
    url(r'^cancel/(?P<scenario_id>[0-9]+)$', RegistCancel.as_view(), name="cancel"),
    #url(r'^api/scenario/(?P<scenario_id>[0-9]+)$', ScenarioDetailApi.as_view()),
    url(r'^api/character$', CharacterApi.as_view()),
    url(r'^api/player', PlayerApi.as_view()),
    url(r'^api/scenario', ScenarioApi.as_view()),
    url(r'^admin/', admin.site.urls),
]

mysite/apps/character/models.py
# -*- coding:utf-8 -*-

# Python Module
from __future__ import unicode_literals

# Django Module
from django.db import models
from django.utils.translation import ugettext_lazy as _

# Third Party Library

# Local Module

# Inner Module


class Character(models.Model):
    """
    캐릭터 정보
    """

    ######
    # Class 변수 선언
    ######
    EMPTY, BOOKED, PAID = range(0, 3)
    CHARACTER_STATUS = (
        (EMPTY, _('Empty')),
        (BOOKED, _('Booked')),
        (PAID, _('Paid'))
    )

    name = models.CharField(
        _("Character_Name"),
        max_length=128
    )

    scenario = models.ForeignKey(
        'scenario.Scenario',
        related_name='character',
        verbose_name=_('Scenario'),
        on_delete=models.CASCADE
    )

    player = models.ForeignKey(
        'player.Player',
        related_name='character',
        verbose_name=_('Player'),
        blank=True,
        null=True,
        on_delete=models.SET_NULL
    )

    status = models.PositiveSmallIntegerField(
        _("Status of booking"),
        choices=CHARACTER_STATUS,
        default=EMPTY
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('scenario',)
        verbose_name = _('Character')
        verbose_name_plural = _("Characters")

mysite/apps/player/models.py
# -*- coding:utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _


class Player(models.Model):
    """
    플레이어 정보
    """
    ######
    # Class 변수 선언
    ######
    MALE, FEMALE = True, False
    GENDER_CHOICES = (
        (MALE, _('Male')),
        (FEMALE, _('Female'))
    )

    YES, NO = True, False
    ADULT_CHOICES = (
        (YES, _('Yes')),
        (NO, _('No'))
    )

    name = models.CharField(
        _("Player Name"),
        max_length=64
    )

    nickname = models.CharField(
        _("Player Nickname"),
        max_length=64
    )

    phone_number = models.CharField(
        _("Phone Number"),
        max_length=16
    )

    gender = models.BooleanField(
        _("Gender"),
        choices=GENDER_CHOICES,
        default=MALE
    )

    is_adult = models.BooleanField(
        _("Is Adult"),
        choices=ADULT_CHOICES,
        default=YES
    )

    email = models.EmailField(
        _("Email"),
        max_length=64
    )

    reg_date = models.DateTimeField(
        _("Reg Date"),
        auto_now_add=True
    )

    modify_date = models.DateTimeField(
        _("Modify Date"),
        auto_now=True
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Player')
        verbose_name_plural = _("Players")

mysite/apps/scenario/models.py
# -*- coding:utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _


class Scenario(models.Model):
    """
    시나리오 정보
    """

    ######
    # Class 변수 선언
    ######
    INACTIVE, ACTIVE = False, True
    SCENARIO_STATUS = (
        (INACTIVE, _('Inactive')),
        (ACTIVE, _('Active'))
    )

    FREE, MALE_ONLY, FEMALE_ONLY = None, True, False
    GENDER_CHOICES = (
        (FREE, _('Free')),
        (MALE_ONLY, _('Male Only')),
        (FEMALE_ONLY, _('Female Only'))
    )

    YES, NO = True, False
    ADULT_CHOICES = (
        (YES, _('Adult Only')),
        (NO, _('Free'))
    )

    master = models.CharField(
        _("Master Name"),
        max_length=64,
        null=True
    )

    name = models.CharField(
        _("Scenario Name"),
        max_length=128
    )

    adult_only = models.BooleanField(
        _("Adult Only"),
        choices=ADULT_CHOICES,
        default=NO
    )

    gender_only = models.NullBooleanField(
        _("Gender Only"),
        default=None,
        choices=GENDER_CHOICES
    )

    is_active = models.BooleanField(
        _("Is Active"),
        choices=SCENARIO_STATUS,
        default=ACTIVE
    )

    reg_date = models.DateTimeField(
        _("Reg Date"),
        auto_now_add=True
    )

    modify_date = models.DateTimeField(
        _("Modify Date"),
        auto_now=True
    )

    def __str__(self):
        return self.name

    def get_characters(self):
        return self.character.all()

    class Meta:
        verbose_name = _('Scenario')
        verbose_name_plural = _("Scenarios")

mysite/apps/player/forms.py
# -*- coding:utf-8 -*-

# Python Module

# Django Module
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.apps import apps

# Third Party Library

# Local Module

# Inner Module
from .models import Player

# Local Model
Scenario = apps.get_app_config('scenario').get_model('Scenario')
Character = apps.get_app_config('character').get_model('Character')


class RegistForm(forms.Form):
    scenario = forms.ModelChoiceField(
        queryset=Scenario.objects.filter(is_active=Scenario.ACTIVE),
        empty_label="",
    )

    character = forms.ModelChoiceField(
        queryset=Character.objects.all(),
        empty_label="",
    )

    player_name = forms.CharField(max_length=64)
    player_nickname = forms.CharField(max_length=64)
    player_phone_number = forms.CharField(max_length=16)
    player_gender = forms.ChoiceField(choices=Player.GENDER_CHOICES)
    player_adult = forms.ChoiceField(choices=Player.ADULT_CHOICES)
    player_email = forms.EmailField(max_length=64)

    agree_read_all = forms.BooleanField()
    agree_no_problem = forms.BooleanField()
    agree_face = forms.BooleanField()


class CancelForm(forms.Form):
    scenario_id = forms.IntegerField()
    character_id = forms.IntegerField()
    player_name = forms.CharField(max_length=64)
    player_phone_number = forms.CharField(max_length=16)
    player_email = forms.EmailField(max_length=64)
    agree_cancel = forms.BooleanField()

mysite/apps/character/views.py
# -*- coding:utf-8 -*-

# Python Module

# Django Module
from django.http import HttpResponse

# Third Party Library
from rest_framework.views import APIView
from rest_framework.renderers import JSONRenderer

# Local Module
from .models import Character
from .serializer import CharacterSerializer

# Inner Module


class CharacterApi(APIView):
    @staticmethod
    def get(request):
        """
        hello
        ---
        response_serializer: CharacterSerializer
        parameters:
            - name: id
              required: false
              type: integer
              paramType: query
        """
        if 'id' in request.GET and request.GET['id']:
            data = Character.objects.filter(id=request.GET['id'])
        elif 'scenario_id' in request.GET and request.GET['scenario_id']:
            data = Character.objects.filter(
                scenario=request.GET['scenario_id'],
                status=Character.EMPTY
            )
        else:
            data = Character.objects.all()

        data = CharacterSerializer(data, many=True).data

        return HttpResponse(JSONRenderer().render(data))

    @staticmethod
    def post(self):
        """
        hello
        ---
        response_serializer: CharacterSerializer
        parameters:
            - name: id
              required: false
              type: integer
              paramType: query
        """
        pass

mysite/apps/player/views.py
# -*- coding:utf-8 -*-

# Python Module

# Django Module
from django.http import HttpResponse, HttpResponseRedirect
from django.views import View
from django.views.generic.base import TemplateView
from django.utils.translation import ugettext_lazy as _
from django.db import transaction
from django.apps import apps

# Third Party Library
from rest_framework.views import APIView
from rest_framework.renderers import JSONRenderer

# Local Module

# Inner Module
from .models import Player
from .forms import RegistForm, CancelForm
from .serializer import PlayerSerializer

# Local Model
Scenario = apps.get_app_config('scenario').get_model('Scenario')
Character = apps.get_app_config('character').get_model('Character')
Mail = apps.get_app_config('mail').get_model('Mail')


class Regist(View):
    def get(self, request):
        return HttpResponse("")

    def post(self, request):
        return HttpResponse("")


class PlayerApi(APIView):
    @staticmethod
    def get(request):
        """
        Provide Scenario information
        ---
        response_serializer: PlayerSerializer
        parameters:
            - name: id
              required: false
              type: integer
              paramType: query
        """
        if 'id' in request.GET and request.GET['id']:
            data = Player.objects.filter(id=request.GET['id'])
        else:
            data = Player.objects.all()

        data = PlayerSerializer(data, many=True).data

        return HttpResponse(JSONRenderer().render(data))


class PlayerRegist(TemplateView):
    """
    User Registraion View
    """
    template_name = "player/player_regist.html"

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        context['scenarios'] = Scenario.objects.filter(is_active=True)
        context['form'] = RegistForm()
        context['success'] = 'GET'

        return self.render_to_response(context)

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        form = RegistForm(request.POST)
        context = self.get_context_data(**kwargs)
        context['success'] = 'POST_SUCCESS'
        context['error'] = "실패 사유"

        if form.is_valid():
            scenario = form.cleaned_data['scenario']

            gender_only = scenario.gender_only
            player_gender = form.cleaned_data['player_gender']
            if gender_only != Scenario.FREE:
                if gender_only == Scenario.MALE_ONLY and player_gender != str(Player.MALE):
                    context['success'] = 'POST_FAIL'
                    context['error'] += "\n남성 전용 시나리오입니다."
                elif gender_only == Scenario.FEMALE_ONLY and player_gender != str(Player.FEMALE):
                    context['success'] = 'POST_FAIL'
                    context['error'] += "\n여성 전용 시나리오입니다."
            if scenario.adult_only == Scenario.YES and form.cleaned_data['player_adult'] != str(Player.YES):
                context['success'] = 'POST_FAIL'
                context['error'] += "\n성인 전용 시나리오입니다."

            character = form.cleaned_data['character']
            if character.status != Character.EMPTY:
                context['success'] = 'POST_FAIL'
                context['error'] += "\n불행! 누군가 캐릭터를 선점 했습니다. 다른 캐릭터를 선택해주세요."

            if context['success'] == 'POST_SUCCESS':
                player = Player.objects.create(
                    name=form.cleaned_data['player_name'],
                    nickname=form.cleaned_data['player_nickname'],
                    phone_number=form.cleaned_data['player_phone_number'],
                    gender=form.cleaned_data['player_gender'],
                    is_adult=form.cleaned_data['player_adult'],
                    email=form.cleaned_data['player_email']
                )
                player.save()

                character.status = Character.BOOKED
                character.player = player
                character.save()

                mail = Mail.objects.create(
                    player_name=player.name,
                    scenario_name=scenario.name,
                    character_name=character.name,
                    player_reg_date=player.reg_date,
                    player_email=player.email,
                    player_phone_number=player.phone_number
                )
                mail.save()

                context['form'] = RegistForm
            else:
                context['form'] = form
                context['fail_character'] = Character.objects\
                    .filter(scenario=form.cleaned_data['scenario'])\
                    .filter(status=Character.EMPTY)
        else:
            context['success'] = 'POST_FAIL'
            context['error'] += '잘못된 입력값'
            context['form'] = form
            context['fail_character'] = []

        context['scenarios'] = Scenario.objects.filter(is_active=True)

        return self.render_to_response(context)


class RegistCancel(TemplateView):
    """
    Regist Cancel View
    """
    template_name = "player/regist_cancel.html"

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        scenario = Scenario.objects.get(id=kwargs['scenario_id'])
        context['scenario'] = scenario
        context['characters'] = scenario.character.filter(status=Character.BOOKED)
        context['form'] = CancelForm()
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        form = CancelForm(request.POST)
        context = self.get_context_data(**kwargs)
        context['success'] = "입력칸을 채워주세요!"
        scenario = Scenario.objects.get(id=request.POST['scenario_id'])
        if form.is_valid():
            character = Character.objects.get(id=form.cleaned_data['character_id'])
            player = character.player
            context['success'] = "정보가 일치하지 않습니다"
            if form.cleaned_data['player_email'] == player.email and \
                form.cleaned_data['player_name'] == player.name and \
                form.cleaned_data['player_phone_number'] == player.phone_number:
                player.delete()
                character.player = None
                character.status = Character.EMPTY
                character.save()
                context['success'] = "취소됐습니다!"
                return HttpResponseRedirect('/')
        context['scenario'] = scenario
        context['characters'] = scenario.character.filter(status=Character.BOOKED)
        context['form'] = form
        return self.render_to_response(context)

mysite/apps/scenario/views.py
# -*- coding:utf-8 -*-

# Python Module

# Django Module
from django.http import HttpResponse

# Third Party Library
from rest_framework.views import APIView
from rest_framework.renderers import JSONRenderer

# Local Module

# Inner Module
from .models import Scenario
from .serializer import ScenarioSerializer


class ScenarioApi(APIView):
    @staticmethod
    def get(request):
        """
        Provide Scenario information
        ---
        response_serializer: ScenarioSerializer
        parameters:
            - name: scenario_id
              required: false
              type: integer
              paramType: query
        """

        if 'id' in request.GET and request.GET['id']:
            data = Scenario.objects.filter(id=request.GET['id'])
        else:
            data = Scenario.objects.all()

        data = ScenarioSerializer(data, many=True).data

        return HttpResponse(JSONRenderer().render(data))

mysite/templates/player/player_regist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static "css/player_regist.css" %}">
    <script
        src="https://code.jquery.com/jquery-3.2.0.min.js"
        integrity="sha256-JAW99MJVpJBGcbzEuXk4Az05s/XyDdBomFqNlM3ic+I="
        crossorigin="anonymous"></script>
    <script src="{% static "js/player_regist.js" %}"></script>
    <title>행사 신청</title>
</head>
<body>
    {% if success == 'POST_SUCCESS' %}<div style="background-color: #03A9F4; line-height: 40px; text-align: center; color: #ffffff;">신청 완료!</div>{% endif %}
    {% if success == 'POST_FAIL' %}<div style="background-color: #FF5722; line-height: 30px; text-align: center; color: #ffffff;">{{ error | linebreaksbr }}</div>{% endif %}
    <div class="container body">
        <div class="header_container">
            <div class="header_title"><b style="color: #FE9600">할로윈</b> 파티 신청 페이지</div>
        </div>
        <div class="body_container">
            <form class="regist_form" id="regist_form" method="post" action="{% url "regist" %}">
                {% csrf_token %}
                <div class="table_container">
                    <div class="table_title">테이블 정보</div>
                    <div class="table_detail">
                        <div class="table_scenario">
                            <label for="scenario" class="table_scenario_title">게임명</label>
                            {{ form.scenario }}
                        </div>
                        <div class="table_character">
                            <label for="character" class="table_character_title">캐릭터</label>
                            <select id="id_character" name="character" required>
                                {% if success == 'POST_FAIL' %}
                                    {% for character in fail_character %}
                                        <option value="{{ character.id }}">{{ character.name }}</option>
                                    {% endfor %}
                                {% endif %}
                            </select>
                        </div>
                    </div>
                </div>
                <div class="player_container">
                    <div class="player_title">플레이어 정보</div>
                    <div class="player_detail">
                        <div class="player_detail_basic">
                            <div class="player_detail_name">
                                <label for="player_name" class="player_name_title">입금자명</label>
                                {{ form.player_name }}
                            </div>
                            <div class="player_detail_nickname">
                                <label for="player_nickname" class="player_nickname_title">닉네임</label>
                                {{ form.player_nickname }}
                            </div>
                            <div class="player_detail_phone_number">
                                <label for="player_phone_number" class="player_phone_number_title">연락처 (HP)</label>
                                {{ form.player_phone_number }}
                            </div>
                        </div>
                        <div class="player_detail_other">
                            <div class="player_detail_email">
                                <label for="player_email" class="player_email">이메일 주소</label>
                                {{ form.player_email }}
                            </div>
                            <div class="player_detail_gender">
                                <label for="player_gender" class="player_gender_title">성별</label>
                                {{ form.player_gender }}
                            </div>
                            <div class="player_detail_adult">
                                <label for="player_adult" class="player_adult_title">법적 성인이십니까?</label>
                                {{ form.player_adult }}
                            </div>
                        </div>
                        <div class="player_detail_check">
                            <div class="player_agree">
                                <div class="player_agree_checkboxes">
                                    {{ form.agree_read_all }}
                                    {{ form.agree_no_problem }}
                                    {{ form.agree_face }}
                                </div>
                                <div class="player_agree_lables">
                                    <label for="agree_read_all">신청하려는 행사의 모든 유의사항을 읽었습니다.</label>
                                    <label for="agree_no_problem">신청하려는 행사의 제한 조건에 결격사유가 없습니다.</label>
                                    <label for="agree_fact">입력한 정보가 모두 사실임을 확인했습니다.</label>
                                </div>
                            </div>
                            <input type="submit" class="player_submit" id="player_submit" value="신청 !">
                        </div>
                    </div>
                </div>
            </form>
            <div class="player_warning">
                * 신청시 입력한 내용이 허위로 밝혀질 경우 신청료 환불 없이 예약이 취소될 수 있습니다.<br>
                * 24시간 이내 입금이 확인되지 않으면 통보 없이 신청이 취소됩니다.<br>
                * 행사 당일, 시작 시간에서 30분이 지나면 입장이 불가능합니다.<br>
                * 이메일 오기재 등으로 신청 확인 메일을 수신하지 못하신 경우, NAVER TRPG CAFE 내 '카페 요청 사항' 게시판으로 문의 주세요.<br>
                * 행사장 내에서 냄새가 심한 음식의 취식(컵라면) 및 흡연은 금지됩니다.<br>
                * 행사장 내 주차 공간이 존재하지 않으니 대중교통을 이용 부탁드립니다<br>
                * <span style="color: red">아래(신청 현황)의 게임명을 클릭해서 <b>신청을 취소</b>할 수 있습니다</span><br>
            </div>
        </div>
        <div class="footer_container">
            <div class="footer_title">신청 현황</div>
            <div class="footer_scenario_container">
            {% for scenario in scenarios %}
                <div class="footer_scenario">
                    <div class="footer_scenario_title">
                        <a class="scenario_name" href="/cancel/{{ scenario.id }}">{{ scenario.name|truncatechars:23 }}</a>
                        {% if scenario.master != None %}
                            <span class="scenario_master">{{ scenario.master }} </span>
                        {% endif %}
                    </div>
                    <div class="footer_scenario_booked">
                    {% for character in scenario.character.all %}
                        <div class="scenario_character_status"
                        {% if character.status == 0 %}
                            style="background-color: #8bc34a; border-color: #5b8031;"
                        {% elif character.status == 1 %}
                            style="background-color: #ffc107; border-color: #b38805;"
                        {% elif character.status == 2 %}
                            style="background-color: #ff8000; border-color: #b37100;"
                        {% else %}
                            style="background-color: #bdbdbd; border-color: #757575;"
                        {% endif %}
                        ></div>
                    {% endfor %}
                    </div>
                    <div class="footer_scenario_detail">
                        자세히 보기 !
                        <div class="detail_view">
                            << {{ scenario.master }}: {{ scenario.name }} >><br><br>
                        {% for character in scenario.character.all %}
                            캐릭터명: <b>{{ character.name }}</b><br>
                            신청자 별명: {{ character.player.nickname }}<br>
                            신청 상태: <span style="color: {% if character.status == 0 %}#8bc34a">신청 가능{% elif character.status == 1 %}#ffc107">예약됨(미입금){% else %}#ff8000">예약됨(입금완료){% endif %}</span><br>
                            신청 시간: {{ character.player.reg_date|date:'Y-m-d H:i' }}<br>
                            -----------------------------------<br>
                        {% endfor %}
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
            <div class="footer_status_explain">
                <div class="explain_title">현황 안내 보는 법</div>
                <div class="explain_body">
                    <div class="explain_color">
                        <div class="color_box" style="background-color: #8bc34a; border-color: #5b8031"></div>
                        <div class="color_box" style="background-color: #ffc107; border-color: #b38805"></div>
                        <div class="color_box" style="background-color: #ff8000; border-color: #b37100"></div>
                        <div class="color_box" style="background-color: #bdbdbd; border-color: #757575"></div>
                    </div>
                    <div class="explain_text">
                        <div class="color_text">신청 가능</div>
                        <div class="color_text">예약됨 (입금대기중)</div>
                        <div class="color_text">예약 및 입금 완료</div>
                        <div class="color_text">신청 불가능</div>
                    </div>
                </div>
            </div>
        </div>
        <div style="text-align:center; width: 100%; margin-top: 100px">
            <img style="margin: auto;" src="{% static "photo.png" %}">
        </div>
    </div>
</body>
</html>

mysite/templates/player/regist_cancel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static "css/regist_cancel.css" %}">
    <title>신청 취소</title>
</head>
<body>
<div class="container body">
    <div class="header_container">
        <a href="/"><div class="header_title">{% if success %}{{ success }}{% else %}신청 페이지로{% endif %}</div></a>
    </div>
    <div class="body_container">
        <form class="cancel_form" id="cancel_form" method="post" action="">
            {% csrf_token %}
            <input type="hidden" name="scenario_id" value={{ scenario.id }}>
            <div class="table_container">
                <div class="table_title">취소 정보</div>
                <div class="table_detail">
                    <div class="table_scenario">
                        <label for="scenario" class="table_scenario_title">게임명</label>
                        <select disabled class="scenario_name" name="scenario_id" required>
                            <option selected value={{ scenario.id }}>{{ scenario.name }}</option>
                        </select>
                    </div>
                    <div class="table_character">
                        <label for="character" class="table_character_title">캐릭터</label>
                        <select id="id_character" name="character_id" required>
                            {% for c in characters %}
                                <option value={{ c.id }}>{{ c.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
            <div class="player_container">
                <div class="player_title">플레이어 정보</div>
                <div class="player_detail">
                    <div class="player_detail_basic">
                        <div class="player_detail_name">
                            <label for="player_name" class="player_name_title">입금자명</label>
                            {{ form.player_name }}
                        </div>
                        <div class="player_detail_phone_number">
                            <label for="player_phone_number" class="player_phone_number_title">연락처 (HP)</label>
                            {{ form.player_phone_number }}
                        </div>
                        <div class="player_detail_email">
                            <label for="player_email" class="player_email">이메일 주소</label>
                            {{ form.player_email }}
                        </div>
                    </div>
                    <div class="player_detail_check">
                        <div class="player_agree">
                            <div class="player_agree_checkboxes">
                                {{ form.agree_cancel }}
                            </div>
                            <div class="player_agree_lables">
                                <label for="agree_read_all">신청 취소에 동의합니다.</label>
                            </div>
                        </div>
                        <input type="submit" class="player_submit" id="player_submit" value="신청 취소">
                    </div>
                </div>
            </div>
        </form>
        <div class="player_warning">
        * 신청시 입력한 정보와 동일한 이름, 연락처, 이메일 주소가 필요합니다.<br>
        * 이미 입금이 완료된 경우, 안전한 환불을 위해 신청 사이트에서 취소가 불가능합니다. 관리자에게 문의하십시오.<br>
        </div>
    </div>
</div>
</body>
</html>